// packages/angular/src/mocksee.component.ts
import {
    Component,
    Input,
    inject,
    signal,
    computed,
    HostListener,
    ChangeDetectionStrategy,
} from "@angular/core"
import { CommonModule } from "@angular/common"
import { MockSeeService } from "./mocksee.service"
import {
    mergeTheme,
    applyColorOverrides,
    getContainerStyles,
    getLabelStyles,
    getTooltipStyles,
    getArrowStyles,
    parseMarkdown,
} from "@mocksee/core"
import type { MockSeeVariant, TooltipFormat } from "@mocksee/core"

@Component({
    selector: "mock-see",
    standalone: true,
    imports: [CommonModule],
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <div
            [ngStyle]="shouldShowIndicator() ? containerStyle() : null"
            (mouseenter)="onMouseEnter()"
            (mouseleave)="onMouseLeave()"
        >
            @if (shouldShowIndicator()) {
                <div
                    [ngStyle]="labelStyle()"
                    (click)="onLabelClick($event)"
                    [attr.role]="isClickable() ? 'button' : null"
                    [attr.tabindex]="isClickable() ? 0 : null"
                >
                    {{ label }}
                </div>
                @if (tooltipText()) {
                    <div
                        [ngStyle]="tooltipStyle()"
                        role="tooltip"
                        [attr.aria-hidden]="!tooltipVisible()"
                    >
                        <div [ngStyle]="arrowStyle()"></div>
                        @if (tooltipHtml()) {
                            <div [innerHTML]="tooltipHtml()"></div>
                        } @else {
                            {{ tooltipText() }}
                        }
                    </div>
                }
            }
            <ng-content></ng-content>
        </div>
    `,
})
export class MockSeeComponent {
    private readonly mockSeeService = inject(MockSeeService)

    @Input() label = "MOCK"
    @Input() reason?: string
    @Input() description?: string
    @Input() variant?: MockSeeVariant
    @Input() disabled = false
    @Input() format: TooltipFormat = "text"
    @Input() labelBg?: string
    @Input() labelColor?: string
    @Input() borderColor?: string
    @Input() tooltipBg?: string
    @Input() tooltipColor?: string

    protected readonly config = this.mockSeeService.config
    protected readonly tooltipVisible = signal(false)

    protected readonly resolvedVariant = computed(
        () => this.variant ?? this.config().defaultVariant
    )

    protected readonly shouldShowIndicator = computed(
        () => !this.disabled && this.config().enabled
    )

    protected readonly theme = computed(() => {
        const baseTheme = mergeTheme(this.config().theme)
        return applyColorOverrides(baseTheme, {
            labelBg: this.labelBg,
            labelColor: this.labelColor,
            borderColor: this.borderColor,
            tooltipBg: this.tooltipBg,
            tooltipColor: this.tooltipColor,
        })
    })

    protected readonly tooltipText = computed(() => this.reason ?? this.description)

    protected readonly tooltipHtml = computed(() =>
        this.format === "markdown" && this.tooltipText()
            ? parseMarkdown(this.tooltipText()!)
            : null
    )

    protected readonly isClickable = computed(
        () => this.config().tooltipTrigger === "click" && !!this.tooltipText()
    )

    protected readonly containerStyle = computed(() =>
        getContainerStyles({
            variant: this.resolvedVariant(),
            theme: this.theme(),
        })
    )

    protected readonly labelStyle = computed(() =>
        getLabelStyles({
            variant: this.resolvedVariant(),
            theme: this.theme(),
            isClickable: this.isClickable(),
        })
    )

    protected readonly tooltipStyle = computed(() =>
        getTooltipStyles({
            variant: this.resolvedVariant(),
            theme: this.theme(),
            visible: this.tooltipVisible(),
        })
    )

    protected readonly arrowStyle = computed(() => getArrowStyles(this.theme()))

    @HostListener("document:click")
    onDocumentClick(): void {
        if (this.config().tooltipTrigger === "click") {
            this.tooltipVisible.set(false)
        }
    }

    protected onMouseEnter(): void {
        if (this.config().tooltipTrigger === "hover" && this.tooltipText()) {
            this.tooltipVisible.set(true)
        }
    }

    protected onMouseLeave(): void {
        if (this.config().tooltipTrigger === "hover") {
            this.tooltipVisible.set(false)
        }
    }

    protected onLabelClick(event: Event): void {
        if (this.isClickable()) {
            event.stopPropagation()
            this.tooltipVisible.update((v) => !v)
        }
    }
}

// packages/react/src/MockSee.tsx
"use client"

import * as React from "react"
import { useMockSee } from "./context"
import type { MockSeeProps } from "./types"
import {
    mergeTheme,
    applyColorOverrides,
    getContainerStyles,
    getLabelStyles,
    getTooltipStyles,
    getArrowStyles,
    parseMarkdown,
} from "@mocksee/core"

/**
 * Development-only visual indicator for components using mock data.
 * 
 * Wraps children with a visual indicator (border, badge, or minimal)
 * to highlight that the content is using mock/placeholder data.
 * 
 * In production, this component is a no-op and returns children directly
 * when the provider's `enabled` prop is false.
 * 
 * @example
 * ```tsx
 * <MockSee label="API Data" reason="Not connected to backend">
 *   <UserList users={mockUsers} />
 * </MockSee>
 * ```
 */
export function MockSee({
    label = "MOCK",
    reason,
    description,
    variant,
    disabled = false,
    format = "text",
    children,
    className,
    style,
    labelBg,
    labelColor,
    borderColor,
    tooltipBg,
    tooltipColor,
}: MockSeeProps) {
    const config = useMockSee()
    const resolvedVariant = variant ?? config.defaultVariant

    // Merge global theme with per-instance overrides
    const baseTheme = mergeTheme(config.theme)
    const theme = applyColorOverrides(baseTheme, {
        labelBg,
        labelColor,
        borderColor,
        tooltipBg,
        tooltipColor,
    })

    const tooltipText = reason ?? description
    const [tooltipVisible, setTooltipVisible] = React.useState(false)

    // Early return if disabled globally or locally
    if (!config.enabled || disabled) {
        return <>{children}</>
    }

    const isClickable = config.tooltipTrigger === "click" && !!tooltipText

    const containerStyle = getContainerStyles({
        variant: resolvedVariant,
        theme,
        baseStyle: style as Record<string, unknown>,
    }) as React.CSSProperties

    const labelStyle = getLabelStyles({
        variant: resolvedVariant,
        theme,
        isClickable,
    }) as React.CSSProperties

    const tooltipStyle = getTooltipStyles({
        variant: resolvedVariant,
        theme,
        visible: tooltipVisible,
    }) as React.CSSProperties

    const arrowStyle = getArrowStyles(theme) as React.CSSProperties

    const handleLabelClick = (e: React.MouseEvent) => {
        if (isClickable) {
            e.stopPropagation()
            setTooltipVisible(!tooltipVisible)
        }
    }

    // For hover mode, handle mouse events on the entire container
    const containerHoverHandlers = config.tooltipTrigger === "hover" && tooltipText
        ? {
            onMouseEnter: () => setTooltipVisible(true),
            onMouseLeave: () => setTooltipVisible(false),
        }
        : {}

    // Close tooltip when clicking outside (for click mode)
    React.useEffect(() => {
        if (config.tooltipTrigger === "click" && tooltipVisible) {
            const handleClickOutside = () => setTooltipVisible(false)
            // Delay to prevent immediate close on the same click
            const timer = setTimeout(() => {
                document.addEventListener("click", handleClickOutside)
            }, 0)
            return () => {
                clearTimeout(timer)
                document.removeEventListener("click", handleClickOutside)
            }
        }
    }, [config.tooltipTrigger, tooltipVisible])

    return (
        <div
            className={className}
            style={containerStyle}
            {...containerHoverHandlers}
        >
            <div
                style={labelStyle}
                onClick={handleLabelClick}
                role={isClickable ? "button" : undefined}
                tabIndex={isClickable ? 0 : undefined}
                onKeyDown={(e) => {
                    if (isClickable && (e.key === "Enter" || e.key === " ")) {
                        e.preventDefault()
                        setTooltipVisible(!tooltipVisible)
                    }
                }}
            >
                {label}
            </div>
            {/* Custom tooltip */}
            {tooltipText && (
                <div style={tooltipStyle} role="tooltip" aria-hidden={!tooltipVisible}>
                    <div style={arrowStyle} />
                    {format === "markdown" ? (
                        <div dangerouslySetInnerHTML={{ __html: parseMarkdown(tooltipText) }} />
                    ) : (
                        tooltipText
                    )}
                </div>
            )}
            {children}
        </div>
    )
}
